### ISSUE TITLE
@ issues the Docker hub pull fails

### ISSUE THREAD

**Issue by dmccullo** [z0ph/aws-security-toolbox#3]
The reason is CONTAINER_IMAGE="aws-security-toolbox" should be CONTAINER_IMAGE="zoph/aws-security-toolbox"

**Comment by z0ph** [comment]
Hello @dmccullo,

Thanks for trying out. This is expected behavior as you should run `./ast.sh build` to build it locally.

As I understand, you are trying to follow the following steps:
1. `docker pull zoph/aws-security-toolbox`
2. Use `ast.sh`using exec or login` and it's not working as the container image is not the same tag `$CONTAINER_IMAGE=aws-security-toolbox`

You are right, I should add a function to pull the official docker hub repository. `./ast.sh pull`

To fix this issue, you should run `docker tag` command
- `docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]`

Let me know if its working for you.
Thanks,
Victor

**Comment by z0ph** [comment]
Fixed in v0.2: https://github.com/z0ph/aws-security-toolbox/tree/v0.2
